package ast.lineaP;

public enum KindAsig{
	TOR, TOZ, POR, DIVENT, MODUL, DIV,
	MAS, MENOS, MAYOR, MENOR, MAYORIGUAL, MENORIGUAL,
	IGUAL, DISTINTO, ON, OFF,
	OR, AND, NEGACION, AMPERSAND, BARRABAJA;
}