
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 19 19:30:57 CEST 2025
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int SREAD = 49;
  public static final int DISTINTO = 16;
  public static final int CHAIN = 39;
  public static final int DIVENT = 6;
  public static final int RENAME = 53;
  public static final int RNUM = 33;
  public static final int POR = 4;
  public static final int SWRITE = 50;
  public static final int MASPREF = 8;
  public static final int STATE = 34;
  public static final int CCIERRE = 25;
  public static final int ZREAD = 45;
  public static final int PCIERRE = 23;
  public static final int LCIERRE = 27;
  public static final int LAP = 26;
  public static final int EACH = 57;
  public static final int CAP = 24;
  public static final int PUNTOCOMA = 30;
  public static final int FOR = 56;
  public static final int DELETE = 64;
  public static final int OFF = 36;
  public static final int DEFINE = 65;
  public static final int RREAD = 47;
  public static final int AND = 37;
  public static final int MENORIGUAL = 21;
  public static final int IGUAL = 15;
  public static final int MODULPREF = 13;
  public static final int BLOCK = 42;
  public static final int IN = 58;
  public static final int OR = 38;
  public static final int ZNUM = 32;
  public static final int ON = 35;
  public static final int DIV = 5;
  public static final int DIVPREF = 11;
  public static final int IF = 59;
  public static final int DIR = 40;
  public static final int AMPERSAND = 63;
  public static final int DIVENTPREF = 12;
  public static final int MAYORIGUAL = 20;
  public static final int EOF = 0;
  public static final int RETURN = 62;
  public static final int ASIG = 14;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int TOZ = 52;
  public static final int MENOSPREF = 9;
  public static final int COMA = 28;
  public static final int NEGACION = 17;
  public static final int MENOS = 3;
  public static final int MENOR = 19;
  public static final int RWRITE = 48;
  public static final int TOR = 51;
  public static final int PORPREF = 10;
  public static final int REAL = 68;
  public static final int MAYOR = 18;
  public static final int ENT = 67;
  public static final int PAP = 22;
  public static final int BARRABAJA = 31;
  public static final int ELSE = 61;
  public static final int ZWRITE = 46;
  public static final int PUNTO = 29;
  public static final int SILENT = 44;
  public static final int IDEN = 66;
  public static final int ENGINE = 43;
  public static final int WHILE = 55;
  public static final int AS = 54;
  public static final int MODUL = 7;
  public static final int ELIF = 60;
  public static final int MAS = 2;
}

